### ISSUE TITLE
Linking to an untyped uri vertex prevents loading

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/gaedo#31]
When trying to load the object, if one of its value is an URI with no type info attached, loading fail with that stack

```
Caused by: com.dooapp.gaedo.blueprints.strategies.UnableToGetVertexTypeException
    at com.dooapp.gaedo.blueprints.strategies.BeanBasedMappingStrategy.getEffectiveType(BeanBasedMappingStrategy.java:124)
    at com.dooapp.gaedo.blueprints.indexable.IndexableGraphBackedFinderService.getEffectiveType(IndexableGraphBackedFinderService.java:200)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService$DelegatingDriver.getEffectiveType(AbstractBluePrintsBackedFinderService.java:76)
    at com.dooapp.gaedo.blueprints.GraphUtils.createInstance(GraphUtils.java:131)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadSingle(BluePrintsPersister.java:509)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObjectProperties(BluePrintsPersister.java:453)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:430)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:404)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadSingle(BluePrintsPersister.java:513)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObjectProperties(BluePrintsPersister.java:453)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:430)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:404)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.loadObject(AbstractBluePrintsBackedFinderService.java:532)
    at com.dooapp.gaedo.blueprints.CollectionLazyLoader.loadCollection(CollectionLazyLoader.java:55)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadCollection(BluePrintsPersister.java:546)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObjectProperties(BluePrintsPersister.java:448)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:430)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.loadObject(BluePrintsPersister.java:404)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.loadObject(AbstractBluePrintsBackedFinderService.java:532)
    at com.dooapp.gaedo.blueprints.GraphQueryStatement.getFirst(GraphQueryStatement.java:108)
```

**Comment by Riduidel** [comment]
Seems to happen in some unknown cases

**Comment by Riduidel** [comment]
Current fixes totally break the PropertyBagTest !
