### ISSUE TITLE
Searching a non-existing item may create it.

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/gaedo#46]
Title says quite all. However let me complete it.
When searching an object using `equalsTo()` predicate in any form, the target of the equalsTo may be created during search.
This issue is currently checked by test `TestFor46#ensureSearchDoesntCreate`

**Comment by Riduidel** [comment]
By adding the test, the issue immediatly revealed itself :+1: 

```
org.neo4j.graphdb.NotInTransactionException
    at org.neo4j.kernel.impl.persistence.PersistenceManager.getResource(PersistenceManager.java:234)
    at org.neo4j.kernel.impl.persistence.PersistenceManager.nodeCreate(PersistenceManager.java:157)
    at org.neo4j.kernel.impl.core.NodeManager.createNode(NodeManager.java:263)
    at org.neo4j.kernel.EmbeddedGraphDbImpl.createNode(EmbeddedGraphDbImpl.java:316)
    at org.neo4j.kernel.EmbeddedGraphDatabase.createNode(EmbeddedGraphDatabase.java:106)
    at com.tinkerpop.blueprints.pgm.impls.neo4j.Neo4jGraph.addVertex(Neo4jGraph.java:210)
    at com.dooapp.gaedo.blueprints.indexable.IndexableGraphBackedFinderService.createEmptyVertex(IndexableGraphBackedFinderService.java:168)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService$DelegatingDriver.createEmptyVertex(AbstractBluePrintsBackedFinderService.java:66)
    at com.dooapp.gaedo.blueprints.BluePrintsPersister.performUpdate(BluePrintsPersister.java:64)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.doUpdate(AbstractBluePrintsBackedFinderService.java:385)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexForInstanceOfDataType(AbstractBluePrintsBackedFinderService.java:457)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexFor(AbstractBluePrintsBackedFinderService.java:408)
    at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexFor(AbstractBluePrintsBackedFinderService.java:414)
    at com.dooapp.gaedo.blueprints.queries.executable.VertexRootsCollector.load(VertexRootsCollector.java:106)
    at com.dooapp.gaedo.blueprints.queries.executable.VertexRootsCollector.visit(VertexRootsCollector.java:111)
    at com.dooapp.gaedo.blueprints.queries.tests.EqualsTo.accept(EqualsTo.java:34)
    at com.dooapp.gaedo.blueprints.queries.tests.EqualsTo.accept(EqualsTo.java:1)
    at com.dooapp.gaedo.blueprints.queries.tests.AndVertexTest.accept(AndVertexTest.java:28)
    at com.dooapp.gaedo.blueprints.queries.tests.AndVertexTest.accept(AndVertexTest.java:1)
    at com.dooapp.gaedo.blueprints.queries.executable.OptimizedGraphExecutableQuery.getPossibleRootsOf(OptimizedGraphExecutableQuery.java:113)
    at com.dooapp.gaedo.blueprints.queries.executable.OptimizedGraphExecutableQuery.getVerticesToExamine(OptimizedGraphExecutableQuery.java:83)
    at com.dooapp.gaedo.blueprints.queries.executable.AbstractGraphExecutableQuery.getVertices(AbstractGraphExecutableQuery.java:32)
    at com.dooapp.gaedo.blueprints.queries.executable.AbstractGraphExecutableQuery.count(AbstractGraphExecutableQuery.java:52)
    at com.dooapp.gaedo.blueprints.GraphQueryStatement.count(GraphQueryStatement.java:69)
    at com.dooapp.gaedo.blueprints.bugs.TestFor46.ensureSearchDoesntCreate(TestFor46.java:61)
```

**Comment by alexblanquart** [comment]
Indeed, this is an issue I found quite recently.

**Comment by Riduidel** [comment]
Issue is resolved for managed objects only, but may appear on literals and tuples
