### ISSUE TITLE
Static method for obtaining id can fail with NullPointerException

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/gaedo#80]
When id value of an object is `null` the line

```
        return service.getIdOf(value).toString();
```

of `GraphUtils#getIdOf` will throw a NullPointerException, which is obviously _bad_.

**Comment by Riduidel** [comment]
Notice it may not be that easy to reproduce, as it happens deep in a stack 

```
Caused by: java.lang.NullPointerException
at com.dooapp.gaedo.blueprints.GraphUtils.getIdOf(GraphUtils.java:220)
at com.dooapp.gaedo.blueprints.transformers.AbstractTupleTransformer.getIdOfTuple(AbstractTupleTransformer.java:65)
at com.dooapp.gaedo.blueprints.transformers.MapEntryTransformer.getIdOfTuple(MapEntryTransformer.java:145)
at com.dooapp.gaedo.blueprints.transformers.MapEntryTransformer.getIdOfTuple(MapEntryTransformer.java:26)
at com.dooapp.gaedo.blueprints.transformers.AbstractTupleTransformer.getVertexFor(AbstractTupleTransformer.java:27)
at com.dooapp.gaedo.blueprints.transformers.MapEntryTransformer.getVertexFor(MapEntryTransformer.java:86)
at com.dooapp.gaedo.blueprints.transformers.MapEntryTransformer.getVertexFor(MapEntryTransformer.java:26)
at com.dooapp.gaedo.blueprints.GraphUtils.getVertexForTuple(GraphUtils.java:300)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexForTuple(AbstractBluePrintsBackedFinderService.java:492)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexFor(AbstractBluePrintsBackedFinderService.java:433)
at com.dooapp.gaedo.blueprints.operations.Updater.createMapVerticesFor(Updater.java:380)
at com.dooapp.gaedo.blueprints.operations.Updater.updateMap(Updater.java:198)
at com.dooapp.gaedo.blueprints.operations.Updater.access$100(Updater.java:34)
at com.dooapp.gaedo.blueprints.operations.Updater$UpdateProperties.operateOnMap(Updater.java:60)
at com.dooapp.gaedo.blueprints.operations.AbstractCardinalityDistinguishingOperation.operateOn(AbstractCardinalityDistinguishingOperation.java:30)
at com.dooapp.gaedo.blueprints.operations.Updater$UpdateProperties.operateOn(Updater.java:35)
at com.dooapp.gaedo.blueprints.operations.OperateOnProperties.execute(OperateOnProperties.java:43)
at com.dooapp.gaedo.blueprints.operations.Updater.updateProperties(Updater.java:155)
at com.dooapp.gaedo.blueprints.operations.Updater.performUpdate(Updater.java:116)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.doUpdate(AbstractBluePrintsBackedFinderService.java:397)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexForInstanceOfDataType(AbstractBluePrintsBackedFinderService.java:485)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexFor(AbstractBluePrintsBackedFinderService.java:420)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.getVertexFor(AbstractBluePrintsBackedFinderService.java:426)
at com.dooapp.gaedo.blueprints.operations.Updater.createCollectionVerticesFor(Updater.java:350)
at com.dooapp.gaedo.blueprints.operations.Updater.updateCollection(Updater.java:251)
at com.dooapp.gaedo.blueprints.operations.Updater.access$200(Updater.java:34)
at com.dooapp.gaedo.blueprints.operations.Updater$UpdateProperties.operateOnCollection(Updater.java:65)
at com.dooapp.gaedo.blueprints.operations.AbstractCardinalityDistinguishingOperation.operateOn(AbstractCardinalityDistinguishingOperation.java:27)
at com.dooapp.gaedo.blueprints.operations.Updater$UpdateProperties.operateOn(Updater.java:35)
at com.dooapp.gaedo.blueprints.operations.OperateOnProperties.execute(OperateOnProperties.java:43)
at com.dooapp.gaedo.blueprints.operations.Updater.updateProperties(Updater.java:155)
at com.dooapp.gaedo.blueprints.operations.Updater.performUpdate(Updater.java:116)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.doUpdate(AbstractBluePrintsBackedFinderService.java:397)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.access$000(AbstractBluePrintsBackedFinderService.java:55)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService$1.doPerform(AbstractBluePrintsBackedFinderService.java:237)
at com.dooapp.gaedo.blueprints.TransactionalOperation.perform(TransactionalOperation.java:56)
at com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService.create(AbstractBluePrintsBackedFinderService.java:233)
... 191 more
```
