### ISSUE TITLE
Loading values from a collection of literal values fail

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/gaedo#82]
And this is a regression !
Stand it simply : CollectionLazyLoader do not read values from field, but simply from remote edges.

**Comment by Riduidel** [comment]
Unfortunatly, present implementation raises NullPointerException for collections having no size virtual property : 

```
Caused by: java.lang.NullPointerException
        at com.dooapp.gaedo.blueprints.CollectionLazyLoader.loadCollection(CollectionLazyLoader.java:143)
        at com.dooapp.gaedo.blueprints.operations.Loader.loadCollection(Loader.java:264)
        at com.dooapp.gaedo.blueprints.operations.Loader.access$200(Loader.java:36)
        at com.dooapp.gaedo.blueprints.operations.Loader$LoadProperties.operateOnCollection(Loader.java:69)
        at com.dooapp.gaedo.blueprints.operations.AbstractCardinalityDistinguishingOperation.operateOn(AbstractCardinalityDistinguishingOperation.java:27)
        at com.dooapp.gaedo.blueprints.operations.Loader$LoadProperties.operateOn(Loader.java:37)
        at com.dooapp.gaedo.blueprints.operations.OperateOnProperties.execute(OperateOnProperties.java:50)
        at com.dooapp.gaedo.blueprints.operations.Loader.loadObjectProperties(Loader.java:140)
        at com.dooapp.gaedo.blueprints.operations.Loader$1.get(Loader.java:115)
        at com.dooapp.gaedo.blueprints.ObjectCache.get(ObjectCache.java:51)
        at com.dooapp.gaedo.blueprints.operations.Loader.loadObject(Loader.java:127)
        at com.dooapp.gaedo.blueprints.operations.Loader.loadObject(Loader.java:86)
        at com.dooapp.gaedo.blueprints.operations.Loader.loadObject(Loader.java:80)
```
